prefix: "<b><#FD9255>MAGMAITEMS</#FD9255> <dark_gray>➡</b> "

bomb:
  allowed-worlds:
    - mina
    - minasvip
    - minapvp
  optimization:
    # ¿Cuántos ticks queremos que dure la explosión VISUAL (rompiendo bloques)?
    # 20 ticks = 1 segundo. 30 ticks = 1.5 segundos.
    target-duration-ticks: 5

    # ¿Cada cuántos ticks se ejecuta un "batch" de borrado? 1 = cada tick.
    delay-between-ticks: 1

    # Límite de seguridad: ¿Cuál es el MÁXIMO de bloques a romper en un solo tick?
    # Esto evita que una bomba GIGANTE (ej. radio 50) intente romper 50,000 bloques en un tick.
    max-blocks-per-batch: 750

drill:
  optimization:
    # ¿Cuántos bloques del pico rompemos por "lote" (batch)?
    # Un valor bajo (10-20) es más seguro para el lag.
    blocks-per-batch: 50
    # ¿Cada cuántos ticks rompemos un lote?
    # 1 = cada tick (más rápido visualmente, un poco más de carga)
    # 2 = cada 2 ticks (más lento, carga más repartida)
    delay-between-ticks: 1
    autosell-worlds:
      - mina
      - minapvp
      - minasvip


totem:
  allowed-worlds:
    - lobby
    - minapvp
    - potpvp
    - world

  sounds:
    use:
      name: "BLOCK_BEACON_POWER_SELECT"
      volume: 1.0
      pitch: 1.2
    consumed:
      name: "ENTITY_ITEM_BREAK"
      volume: 1.0
      pitch: 0.8
  particles:
    type: "TOTEM_OF_UNDYING"
    count: 50
    offset: 0.5
    speed: 0.1

messages:
  no-permission: "<red>No tienes permiso para usar este comando."
  usage: "<gray>Uso: /magmaitem [give|reload|applyid|storage|history|checkduplicates|unblacklist]"
  give-usage: "<gray>Uso: /magmaitem give <player> <item> [amount]"
  player-not-found: "<red>Jugador '%player%' no encontrado o está desconectado."
  item-not-found: "<red>El ítem '%item%' no existe."
  invalid-amount: "<red>La cantidad debe estar entre 1 y 64."
  invalid-number: "<red>Cantidad inválida: Debe ser un número."
  give-success: "<green>Se dio exitosamente <yellow>%amount%x %item% <green>a <yellow>%player%<green>."
  player-only: "<red>Este comando solo puede ser ejecutado por un jugador."
  reload-success: "<green>Configuración recargada exitosamente."
  teleport-success: "<green>Teletransportado a <yellow>%player%"
  player-offline: "<red>El jugador no está en línea/conectado."

  bomb-cooldown: "§x§F§F§3§4§5§8§lDINAMITA §8➡ §f¡Debes esperar §e{time} §fantes de usar otra dinamita!"
  bomb-sale-chat: "§x§F§F§3§4§5§8§lAUTOSELL §8➡ §f¡Has vendido §e{items} §fitems por §x§5§9§f§f§2§0${money}§f!"
  bomb-sale-title: ""
  bomb-sale-subtitle: "§x§5§9§f§f§2§0+${money}"
  world-not-allowed: "§x§F§F§3§4§5§8§lDINAMITA §8➡ §f¡No puedes §cusar §fdinamitas aquí!"

  already-has-id: "<red>Este ítem ya tiene una ID única."
  custom-id-exists: "<red>La ID '%id%' ya existe. Por favor, elige una diferente."
  no-item-in-hand: "<red>Debes sostener un ítem en tu mano principal."
  id-applied: "<green>Se ha asignado una ID única al ítem."

  storage-usage: "<gray>Uso: /magmaitem storage [save|give|list|remove]"

  storage-save-usage: "<gray>Uso: /magmaitem storage save <name>"
  storage-save-success: "<green>Ítem guardado exitosamente como <yellow>'%name%'<green>."
  storage-item-exists: "<red>Ya existe un ítem con el nombre '%name%' en el almacenamiento."
  storage-save-error: "<red>Fallo al guardar el ítem. Revisa la consola."

  storage-give-usage: "<gray>Uso: /magmaitem storage give <player> <name> [--applyid]"
  storage-item-not-found: "<red>Ítem '%name%' no encontrado en el almacenamiento."
  storage-give-success: "<green>Se dio exitosamente <yellow>1x %item% <green>del almacenamiento a <yellow>%player%<green>."

  storage-remove-usage: "<gray>Uso: /magmaitem storage remove <item_name>"
  storage-remove-success: "<green>Ítem <yellow>'%name%' <green>eliminado exitosamente del almacenamiento."

  storage-list-header: "<gold>--- <yellow> Ítems Almacenados (%count%) <gold>---"
  storage-list-empty: "<yellow> Actualmente no hay ítems almacenados."
  storage-list-content: "<green>Ítems Almacenados: <white>%items%"

  totem-save: "<#FFD700><b>TOTEM</b> <dark_gray>➡</dark_gray> <#CDFFB8>¡El Tótem te ha salvado!</#CDFFB8> <white>Aún le restan <#FFE550>{uses}</#FFE550> usos.</white>"
  totem-consumed: "<#FFD700><b>TOTEM</b> <dark_gray>➡</dark_gray> <#FF5050>El Tótem se ha roto!</#FF5050>"

  cannot-drop: "<red><b>ERROR</b> <dark_gray>▸</dark_gray> <white>¡No puedes tirar este ítem!</white>"
  cannot-interact: "<red><b>ERROR</b> <dark_gray>▸</dark_gray> <white>¡No puedes interactuar con este ítem!</white>"

  history-usage: "<gray>Uso: /magmaitem history [open|remove <ID>]"
  history-remove-usage: "<gray>Uso: /magmaitem history remove <ID>"
  history-id-not-found: "<red>ID de seguimiento '<yellow>%id%<red>' no encontrada."
  history-remove-success: "<green>Datos de seguimiento para la ID '<yellow>%id%<green>' eliminados exitosamente."

  duplicate-check-running: "<yellow>Un chequeo de duplicados ya está en ejecución."
  starting-duplicate-check: "<green>Iniciando chequeo de MagmaItems duplicados..."
  duplicate-check-complete: "<green>Chequeo de duplicados completado. Revisa la consola."
  duplicate-check-error: "<red>Ocurrió un error durante el chequeo de duplicados."


Id-remover-whitelist:
  - DanovaMC

confirmation:
  title: "             ᴄᴏɴғɪʀᴍᴀʀ"
  confirm-text: "<!i><#33FF33><b>CONFIRMAR"
  confirm-lore:
    - '<!i><dark_gray>Descripción'
    - ''
    - '<!i><red>⚠ ¡No podras revertir esto!'
    - '<!i><red>¿Seguro de lo que estas haciendo?'
    - ''
    - '<!i><yellow>▸ ¡Click para confirmar!'
  cancel-text: "<!i><#FF1313><b>CANCELAR"
  cancel-lore:
    - '<!i><dark_gray>Descripción'
    - ''
    - '<!i><gray> ℹ ¿Qué es esto?'
    - '<!i><white> Podras cancelar la operación'
    - ''
    - '<!i><yellow>▸ ¡Click para cancelar!'
  confirm-material: "LIME_STAINED_GLASS_PANE"
  cancel-material: "RED_STAINED_GLASS_PANE"

delete-confirmation:
  title: "      ᴇʟɪᴍɪɴᴀʀ ʀᴇɢɪsᴛʀᴏ"
  confirm-text: "<!i><#33FF33><b>CONFIRMAR BORRADO"
  confirm-lore:
    - '<!i><dark_gray>Acción Irreversible'
    - ''
    - '<!i><red>⚠ ¡Esta acción es permanente!'
    - '<!i><gray>El item no será eliminado, solo'
    - '<!i><gray>su registro en el historial.'
    - ''
    - '<!i><yellow>▸ ¡Click para confirmar!'
  cancel-text: "<!i><#FF1313><b>CANCELAR"
  cancel-lore:
    - '<!i><dark_gray>Acción Segura'
    - ''
    - '<!i><gray>Regresarás al historial de items.'
    - ''
    - '<!i><yellow>▸ ¡Click para cancelar!'
  confirm-material: "LIME_STAINED_GLASS_PANE"
  cancel-material: "RED_STAINED_GLASS_PANE"

menu:
  history-title: "Historial - [%page%/%total%]"
  item-display-name: "&r&6%item_name%"
  previous-page: "&r&fPágina &8▸ &cAnterior"
  close: "&r&fMenú &8▸ §x§f§f§5§8§4§1Cerrar"
  next-page: "&r&fPágina &8▸ &aSiguiente"
  clear-search: "&r&fMenú &8▸ §x§7§6§c§e§f§fBuscar"
  search: "&r&fMenú &8▸ §x§7§6§c§e§f§fBuscar"
  sort-button-title: "&r§fMenú &8▸ §x§b§a§d§3§d§5Orden"