prefix: "<b><#FD9255>MAGMAITEMS</#FD9255> <dark_gray>➡</b> "

bomb:
  allowed-worlds:
    - mina
    - minasvip

totem:
  allowed-worlds:
    - lobby
    - minapvp
    - potpvp
    - world
  sounds:
    use:
      name: "BLOCK_BEACON_POWER_SELECT"
      volume: 1.0
      pitch: 1.2
    consumed:
      name: "ENTITY_ITEM_BREAK"
      volume: 1.0
      pitch: 0.8

messages:
  no-permission: "<red>No tienes permiso para usar este comando."
  usage: "<gray>Uso: /magmaitem [give|reload|applyid|storage|history|checkduplicates]"
  give-usage: "<gray>Uso: /magmaitem give <player> <item> [amount]"
  player-not-found: "<red>Jugador '%player%' no encontrado o está desconectado."
  item-not-found: "<red>El ítem '%item%' no existe."
  invalid-amount: "<red>La cantidad debe estar entre 1 y 64."
  invalid-number: "<red>Cantidad inválida: Debe ser un número."
  give-success: "<green>Se dio exitosamente <yellow>%amount%x %item% <green>a <yellow>%player%<green>."
  player-only: "<red>Este comando solo puede ser ejecutado por un jugador."
  reload-success: "<green>Configuración recargada exitosamente."
  teleport-success: "<green>Teletransportado a <yellow>%player%"
  player-offline: "<red>El jugador no está en línea/conectado."

  bomb-cooldown: "§x§F§F§3§4§5§8§lDINAMITA §8➡ §f¡Debes esperar §e{time} §fantes de usar otra dinamita!"
  bomb-sale-chat: "§x§F§F§3§4§5§8§lDINAMITA §8➡ §f¡Has vendido §e{items} §fitems por §x§5§9§f§f§2§0${money}§f!"
  bomb-sale-title: ""
  bomb-sale-subtitle: "§x§5§9§f§f§2§0+${money}"
  world-not-allowed: "§x§F§F§3§4§5§8§lDINAMITA §8➡ §f¡No puedes §cusar §fdinamitas aquí!"

  already-has-id: "<red>Este ítem ya tiene una ID única."
  custom-id-exists: "<red>La ID '%id%' ya existe. Por favor, elige una diferente."
  no-item-in-hand: "<red>Debes sostener un ítem en tu mano principal."
  id-applied: "<green>Se ha asignado una ID única al ítem."

  storage-usage: "<gray>Uso: /magmaitem storage [save|give|list|remove]"

  storage-save-usage: "<gray>Uso: /magmaitem storage save <name>"
  storage-save-success: "<green>Ítem guardado exitosamente como <yellow>'%name%'<green>."
  storage-item-exists: "<red>Ya existe un ítem con el nombre '%name%' en el almacenamiento."
  storage-save-error: "<red>Fallo al guardar el ítem. Revisa la consola."

  storage-give-usage: "<gray>Uso: /magmaitem storage give <player> <name> [--applyid]"
  storage-item-not-found: "<red>Ítem '%name%' no encontrado en el almacenamiento."
  storage-give-success: "<green>Se dio exitosamente <yellow>1x %item% <green>del almacenamiento a <yellow>%player%<green>."

  storage-remove-usage: "<gray>Uso: /magmaitem storage remove <item_name>"
  storage-remove-success: "<green>Ítem <yellow>'%name%' <green>eliminado exitosamente del almacenamiento."

  storage-list-header: "<gold>--- <yellow> Ítems Almacenados (%count%) <gold>---"
  storage-list-empty: "<yellow> Actualmente no hay ítems almacenados."
  storage-list-content: "<green>Ítems Almacenados: <white>%items%"

  totem-save: "<#FFD700><b>TOTEM</b> <dark_gray>➡</dark_gray> <green>¡El <gold>Tótem de Usos Múltiples</gold> te ha salvado! <gray>Usos restantes: <yellow>{uses}"
  totem-consumed: "<#FFD700><b>TOTEM</b> <dark_gray>➡</dark_gray> <red>El <gold>Tótem de Usos Múltiples</gold> se ha consumido por completo."

confirmation:
  title: "             ᴄᴏɴғɪʀᴍᴀʀ"
  confirm-text: "<!i><#33FF33><b>CONFIRMAR"
  confirm-lore:
    - '<!i><dark_gray>Descripción'
    - ''
    - '<!i><red>⚠ ¡No podras revertir esto!'
    - '<!i><red>¿Seguro de lo que estas haciendo?'
    - ''
    - '<!i><yellow>▸ ¡Click para confirmar!'
  cancel-text: "<!i><#FF1313><b>CANCELAR"
  cancel-lore:
    - '<!i><dark_gray>Descripción'
    - ''
    - '<!i><gray> ℹ ¿Qué es esto?'
    - '<!i><white> Podras cancelar la operación'
    - ''
    - '<!i><yellow>▸ ¡Click para cancelar!'
  confirm-material: "LIME_STAINED_GLASS_PANE"
  cancel-material: "RED_STAINED_GLASS_PANE"

placeholders: []
items: []
custom-items: []